/* tslint:disable */
/* eslint-disable */
/**
 * leviathan
 * lolprodle API server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Guess } from './Guess';
import {
    GuessFromJSON,
    GuessFromJSONTyped,
    GuessToJSON,
} from './Guess';

/**
 * 
 * @export
 * @interface CheckGuessResponse
 */
export interface CheckGuessResponse {
    /**
     * 
     * @type {Guess}
     * @memberof CheckGuessResponse
     */
    guess: Guess;
}

/**
 * Check if a given object implements the CheckGuessResponse interface.
 */
export function instanceOfCheckGuessResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "guess" in value;

    return isInstance;
}

export function CheckGuessResponseFromJSON(json: any): CheckGuessResponse {
    return CheckGuessResponseFromJSONTyped(json, false);
}

export function CheckGuessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckGuessResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guess': GuessFromJSON(json['guess']),
    };
}

export function CheckGuessResponseToJSON(value?: CheckGuessResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'guess': GuessToJSON(value.guess),
    };
}

