/* tslint:disable */
/* eslint-disable */
/**
 * leviathan
 * lolprodle API server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ErrorType = {
    Internal: 'Internal',
    NoRegionPlayersAvailable: 'NoRegionPlayersAvailable',
    NoRegionPodsAvailable: 'NoRegionPodsAvailable',
    InvalidPlayerId: 'InvalidPlayerId',
    InvalidRegion: 'InvalidRegion',
    NoPod: 'NoPod'
} as const;
export type ErrorType = typeof ErrorType[keyof typeof ErrorType];


export function ErrorTypeFromJSON(json: any): ErrorType {
    return ErrorTypeFromJSONTyped(json, false);
}

export function ErrorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorType {
    return json as ErrorType;
}

export function ErrorTypeToJSON(value?: ErrorType | null): any {
    return value as any;
}

