/* tslint:disable */
/* eslint-disable */
/**
 * leviathan
 * lolprodle API server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GuessCategory = {
    Id: 'Id',
    Role: 'Role',
    Country: 'Country',
    FavoriteChamps: 'FavoriteChamps',
    Team: 'Team'
} as const;
export type GuessCategory = typeof GuessCategory[keyof typeof GuessCategory];


export function GuessCategoryFromJSON(json: any): GuessCategory {
    return GuessCategoryFromJSONTyped(json, false);
}

export function GuessCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuessCategory {
    return json as GuessCategory;
}

export function GuessCategoryToJSON(value?: GuessCategory | null): any {
    return value as any;
}

