/* tslint:disable */
/* eslint-disable */
/**
 * leviathan
 * lolprodle API server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GuessCategory } from './GuessCategory';
import {
    GuessCategoryFromJSON,
    GuessCategoryFromJSONTyped,
    GuessCategoryToJSON,
} from './GuessCategory';

/**
 * 
 * @export
 * @interface GuessCategoryResult
 */
export interface GuessCategoryResult {
    /**
     * 
     * @type {GuessCategory}
     * @memberof GuessCategoryResult
     */
    category: GuessCategory;
    /**
     * 
     * @type {boolean}
     * @memberof GuessCategoryResult
     */
    correct: boolean;
    /**
     * 
     * @type {string}
     * @memberof GuessCategoryResult
     */
    guess: string;
}

/**
 * Check if a given object implements the GuessCategoryResult interface.
 */
export function instanceOfGuessCategoryResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "category" in value;
    isInstance = isInstance && "correct" in value;
    isInstance = isInstance && "guess" in value;

    return isInstance;
}

export function GuessCategoryResultFromJSON(json: any): GuessCategoryResult {
    return GuessCategoryResultFromJSONTyped(json, false);
}

export function GuessCategoryResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuessCategoryResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'category': GuessCategoryFromJSON(json['category']),
        'correct': json['correct'],
        'guess': json['guess'],
    };
}

export function GuessCategoryResultToJSON(value?: GuessCategoryResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'category': GuessCategoryToJSON(value.category),
        'correct': value.correct,
        'guess': value.guess,
    };
}

