/* tslint:disable */
/* eslint-disable */
/**
 * leviathan
 * lolprodle API server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GuessCategoryResult } from './GuessCategoryResult';
import {
    GuessCategoryResultFromJSON,
    GuessCategoryResultFromJSONTyped,
    GuessCategoryResultToJSON,
} from './GuessCategoryResult';

/**
 * 
 * @export
 * @interface Guess
 */
export interface Guess {
    /**
     * 
     * @type {Array<GuessCategoryResult>}
     * @memberof Guess
     */
    categories: Array<GuessCategoryResult>;
}

/**
 * Check if a given object implements the Guess interface.
 */
export function instanceOfGuess(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "categories" in value;

    return isInstance;
}

export function GuessFromJSON(json: any): Guess {
    return GuessFromJSONTyped(json, false);
}

export function GuessFromJSONTyped(json: any, ignoreDiscriminator: boolean): Guess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categories': ((json['categories'] as Array<any>).map(GuessCategoryResultFromJSON)),
    };
}

export function GuessToJSON(value?: Guess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categories': ((value.categories as Array<any>).map(GuessCategoryResultToJSON)),
    };
}

