/* tslint:disable */
/* eslint-disable */
/**
 * leviathan
 * lolprodle API server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Player } from './Player';
import {
    PlayerFromJSON,
    PlayerFromJSONTyped,
    PlayerToJSON,
} from './Player';

/**
 * 
 * @export
 * @interface PreviousPlayerResponse
 */
export interface PreviousPlayerResponse {
    /**
     * 
     * @type {Player}
     * @memberof PreviousPlayerResponse
     */
    player: Player;
}

/**
 * Check if a given object implements the PreviousPlayerResponse interface.
 */
export function instanceOfPreviousPlayerResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "player" in value;

    return isInstance;
}

export function PreviousPlayerResponseFromJSON(json: any): PreviousPlayerResponse {
    return PreviousPlayerResponseFromJSONTyped(json, false);
}

export function PreviousPlayerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviousPlayerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'player': PlayerFromJSON(json['player']),
    };
}

export function PreviousPlayerResponseToJSON(value?: PreviousPlayerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'player': PlayerToJSON(value.player),
    };
}

