/* tslint:disable */
/* eslint-disable */
/**
 * leviathan
 * lolprodle API server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetTimeResponse
 */
export interface ResetTimeResponse {
    /**
     * Time left until reset_time_unix_millis
     * @type {number}
     * @memberof ResetTimeResponse
     */
    remainingTimeMillis: number;
    /**
     * 
     * @type {number}
     * @memberof ResetTimeResponse
     */
    resetTimeUnixMillis: number;
}

/**
 * Check if a given object implements the ResetTimeResponse interface.
 */
export function instanceOfResetTimeResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "remainingTimeMillis" in value;
    isInstance = isInstance && "resetTimeUnixMillis" in value;

    return isInstance;
}

export function ResetTimeResponseFromJSON(json: any): ResetTimeResponse {
    return ResetTimeResponseFromJSONTyped(json, false);
}

export function ResetTimeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetTimeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'remainingTimeMillis': json['remaining_time_millis'],
        'resetTimeUnixMillis': json['reset_time_unix_millis'],
    };
}

export function ResetTimeResponseToJSON(value?: ResetTimeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'remaining_time_millis': value.remainingTimeMillis,
        'reset_time_unix_millis': value.resetTimeUnixMillis,
    };
}

