/**
 * leviathan
 * lolprodle API server
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Guess } from '../models/Guess';
import { HttpFile } from '../http/http';

export class CheckGuessResponse {
    'guess': Guess;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "guess",
            "baseName": "guess",
            "type": "Guess",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckGuessResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

