/**
 * leviathan
 * lolprodle API server
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Region } from '../models/Region';
import { HttpFile } from '../http/http';

export class CheckGuessRequest {
    'playerId': string;
    'region': Region;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "playerId",
            "baseName": "player_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "Region",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckGuessRequest.attributeTypeMap;
    }

    public constructor() {
    }
}



