/**
 * leviathan
 * lolprodle API server
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GuessCategory } from '../models/GuessCategory';
import { HttpFile } from '../http/http';

export class GuessCategoryResult {
    'category': GuessCategory;
    'correct': boolean;
    'guess': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "category",
            "baseName": "category",
            "type": "GuessCategory",
            "format": ""
        },
        {
            "name": "correct",
            "baseName": "correct",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "guess",
            "baseName": "guess",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GuessCategoryResult.attributeTypeMap;
    }

    public constructor() {
    }
}



