/**
 * leviathan
 * lolprodle API server
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GuessCategoryResult } from '../models/GuessCategoryResult';
import { HttpFile } from '../http/http';

export class Guess {
    'categories': Array<GuessCategoryResult>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<GuessCategoryResult>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Guess.attributeTypeMap;
    }

    public constructor() {
    }
}

