/**
 * leviathan
 * lolprodle API server
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ResetTimeResponse {
    /**
    * Time left until reset_time_unix_millis
    */
    'remainingTimeMillis': number;
    'resetTimeUnixMillis': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "remainingTimeMillis",
            "baseName": "remaining_time_millis",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "resetTimeUnixMillis",
            "baseName": "reset_time_unix_millis",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ResetTimeResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

